apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 32768
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-external
subsets:
  - addresses:
      - ip: 172.17.0.2
    ports:
      - port: 32769