// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goloco.proto

package golocopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Location) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type LocationRequest struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{1}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type LocationResponse struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocationResponse) Reset()         { *m = LocationResponse{} }
func (m *LocationResponse) String() string { return proto.CompactTextString(m) }
func (*LocationResponse) ProtoMessage()    {}
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{2}
}

func (m *LocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationResponse.Unmarshal(m, b)
}
func (m *LocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationResponse.Marshal(b, m, deterministic)
}
func (m *LocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationResponse.Merge(m, src)
}
func (m *LocationResponse) XXX_Size() int {
	return xxx_messageInfo_LocationResponse.Size(m)
}
func (m *LocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocationResponse proto.InternalMessageInfo

func (m *LocationResponse) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type AllLocationsResponse struct {
	Location             []*Location `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AllLocationsResponse) Reset()         { *m = AllLocationsResponse{} }
func (m *AllLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*AllLocationsResponse) ProtoMessage()    {}
func (*AllLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{3}
}

func (m *AllLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllLocationsResponse.Unmarshal(m, b)
}
func (m *AllLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllLocationsResponse.Marshal(b, m, deterministic)
}
func (m *AllLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllLocationsResponse.Merge(m, src)
}
func (m *AllLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_AllLocationsResponse.Size(m)
}
func (m *AllLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllLocationsResponse proto.InternalMessageInfo

func (m *AllLocationsResponse) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type GetLocationLocationRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocationLocationRequest) Reset()         { *m = GetLocationLocationRequest{} }
func (m *GetLocationLocationRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocationLocationRequest) ProtoMessage()    {}
func (*GetLocationLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{4}
}

func (m *GetLocationLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocationLocationRequest.Unmarshal(m, b)
}
func (m *GetLocationLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocationLocationRequest.Marshal(b, m, deterministic)
}
func (m *GetLocationLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocationLocationRequest.Merge(m, src)
}
func (m *GetLocationLocationRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocationLocationRequest.Size(m)
}
func (m *GetLocationLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocationLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocationLocationRequest proto.InternalMessageInfo

func (m *GetLocationLocationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteLocationLocationRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLocationLocationRequest) Reset()         { *m = DeleteLocationLocationRequest{} }
func (m *DeleteLocationLocationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLocationLocationRequest) ProtoMessage()    {}
func (*DeleteLocationLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{5}
}

func (m *DeleteLocationLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLocationLocationRequest.Unmarshal(m, b)
}
func (m *DeleteLocationLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLocationLocationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLocationLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLocationLocationRequest.Merge(m, src)
}
func (m *DeleteLocationLocationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLocationLocationRequest.Size(m)
}
func (m *DeleteLocationLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLocationLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLocationLocationRequest proto.InternalMessageInfo

func (m *DeleteLocationLocationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletedLocationId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedLocationId) Reset()         { *m = DeletedLocationId{} }
func (m *DeletedLocationId) String() string { return proto.CompactTextString(m) }
func (*DeletedLocationId) ProtoMessage()    {}
func (*DeletedLocationId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{6}
}

func (m *DeletedLocationId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedLocationId.Unmarshal(m, b)
}
func (m *DeletedLocationId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedLocationId.Marshal(b, m, deterministic)
}
func (m *DeletedLocationId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedLocationId.Merge(m, src)
}
func (m *DeletedLocationId) XXX_Size() int {
	return xxx_messageInfo_DeletedLocationId.Size(m)
}
func (m *DeletedLocationId) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedLocationId.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedLocationId proto.InternalMessageInfo

func (m *DeletedLocationId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EmptyMessageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessageRequest) Reset()         { *m = EmptyMessageRequest{} }
func (m *EmptyMessageRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyMessageRequest) ProtoMessage()    {}
func (*EmptyMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{7}
}

func (m *EmptyMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessageRequest.Unmarshal(m, b)
}
func (m *EmptyMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessageRequest.Marshal(b, m, deterministic)
}
func (m *EmptyMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessageRequest.Merge(m, src)
}
func (m *EmptyMessageRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyMessageRequest.Size(m)
}
func (m *EmptyMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessageRequest proto.InternalMessageInfo

type ListSuggestionsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationIds          []string `protobuf:"bytes,2,rep,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSuggestionsRequest) Reset()         { *m = ListSuggestionsRequest{} }
func (m *ListSuggestionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSuggestionsRequest) ProtoMessage()    {}
func (*ListSuggestionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{8}
}

func (m *ListSuggestionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSuggestionsRequest.Unmarshal(m, b)
}
func (m *ListSuggestionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSuggestionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSuggestionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSuggestionsRequest.Merge(m, src)
}
func (m *ListSuggestionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSuggestionsRequest.Size(m)
}
func (m *ListSuggestionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSuggestionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSuggestionsRequest proto.InternalMessageInfo

func (m *ListSuggestionsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListSuggestionsRequest) GetLocationIds() []string {
	if m != nil {
		return m.LocationIds
	}
	return nil
}

type ListSuggestionsResponse struct {
	LocationIds          []string `protobuf:"bytes,1,rep,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSuggestionsResponse) Reset()         { *m = ListSuggestionsResponse{} }
func (m *ListSuggestionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSuggestionsResponse) ProtoMessage()    {}
func (*ListSuggestionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{9}
}

func (m *ListSuggestionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSuggestionsResponse.Unmarshal(m, b)
}
func (m *ListSuggestionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSuggestionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSuggestionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSuggestionsResponse.Merge(m, src)
}
func (m *ListSuggestionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSuggestionsResponse.Size(m)
}
func (m *ListSuggestionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSuggestionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSuggestionsResponse proto.InternalMessageInfo

func (m *ListSuggestionsResponse) GetLocationIds() []string {
	if m != nil {
		return m.LocationIds
	}
	return nil
}

type AdRequest struct {
	ContextKeys          []string `protobuf:"bytes,1,rep,name=context_keys,json=contextKeys,proto3" json:"context_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdRequest) Reset()         { *m = AdRequest{} }
func (m *AdRequest) String() string { return proto.CompactTextString(m) }
func (*AdRequest) ProtoMessage()    {}
func (*AdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{10}
}

func (m *AdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdRequest.Unmarshal(m, b)
}
func (m *AdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdRequest.Marshal(b, m, deterministic)
}
func (m *AdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdRequest.Merge(m, src)
}
func (m *AdRequest) XXX_Size() int {
	return xxx_messageInfo_AdRequest.Size(m)
}
func (m *AdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdRequest proto.InternalMessageInfo

func (m *AdRequest) GetContextKeys() []string {
	if m != nil {
		return m.ContextKeys
	}
	return nil
}

type AdResponse struct {
	Ads                  []*Ad    `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdResponse) Reset()         { *m = AdResponse{} }
func (m *AdResponse) String() string { return proto.CompactTextString(m) }
func (*AdResponse) ProtoMessage()    {}
func (*AdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{11}
}

func (m *AdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdResponse.Unmarshal(m, b)
}
func (m *AdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdResponse.Marshal(b, m, deterministic)
}
func (m *AdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdResponse.Merge(m, src)
}
func (m *AdResponse) XXX_Size() int {
	return xxx_messageInfo_AdResponse.Size(m)
}
func (m *AdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdResponse proto.InternalMessageInfo

func (m *AdResponse) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

type Ad struct {
	UrlRedirect          string   `protobuf:"bytes,1,opt,name=url_redirect,json=urlRedirect,proto3" json:"url_redirect,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{12}
}

func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetUrlRedirect() string {
	if m != nil {
		return m.UrlRedirect
	}
	return ""
}

func (m *Ad) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{13}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Location             []*Location `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1ba30750ab23ca, []int{14}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "goloco.Location")
	proto.RegisterType((*LocationRequest)(nil), "goloco.LocationRequest")
	proto.RegisterType((*LocationResponse)(nil), "goloco.LocationResponse")
	proto.RegisterType((*AllLocationsResponse)(nil), "goloco.AllLocationsResponse")
	proto.RegisterType((*GetLocationLocationRequest)(nil), "goloco.GetLocationLocationRequest")
	proto.RegisterType((*DeleteLocationLocationRequest)(nil), "goloco.DeleteLocationLocationRequest")
	proto.RegisterType((*DeletedLocationId)(nil), "goloco.DeletedLocationId")
	proto.RegisterType((*EmptyMessageRequest)(nil), "goloco.EmptyMessageRequest")
	proto.RegisterType((*ListSuggestionsRequest)(nil), "goloco.ListSuggestionsRequest")
	proto.RegisterType((*ListSuggestionsResponse)(nil), "goloco.ListSuggestionsResponse")
	proto.RegisterType((*AdRequest)(nil), "goloco.AdRequest")
	proto.RegisterType((*AdResponse)(nil), "goloco.AdResponse")
	proto.RegisterType((*Ad)(nil), "goloco.Ad")
	proto.RegisterType((*SearchRequest)(nil), "goloco.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "goloco.SearchResponse")
}

func init() { proto.RegisterFile("goloco.proto", fileDescriptor_7a1ba30750ab23ca) }

var fileDescriptor_7a1ba30750ab23ca = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0x95, 0x21, 0xf0, 0xc1, 0xc0, 0x07, 0x61, 0x1b, 0x82, 0xeb, 0xd2, 0x96, 0xb8, 0x8a, 0x84,
	0xaa, 0x88, 0x54, 0xf4, 0xb2, 0x51, 0x53, 0xda, 0x54, 0x51, 0x14, 0x2a, 0x45, 0xa6, 0xbd, 0xe9,
	0x0d, 0x72, 0xbc, 0x23, 0xd7, 0xaa, 0xc1, 0x8e, 0x77, 0x1d, 0x95, 0x67, 0xe8, 0x1b, 0xf6, 0x69,
	0x2a, 0xdb, 0xbb, 0xc6, 0x98, 0x9f, 0xfe, 0xdd, 0xb1, 0x33, 0x67, 0xce, 0xcc, 0x78, 0xce, 0x11,
	0x50, 0xb7, 0x3d, 0xd7, 0xb3, 0xbc, 0x81, 0x1f, 0x78, 0xdc, 0x23, 0xe5, 0xe4, 0xa5, 0x7f, 0x57,
	0xa0, 0x32, 0xf6, 0x2c, 0x93, 0x3b, 0xde, 0x9c, 0x34, 0xa0, 0xe0, 0x50, 0x55, 0xe9, 0x29, 0xfd,
	0x92, 0x51, 0x70, 0x28, 0xe9, 0xc0, 0x7f, 0x21, 0xc3, 0x60, 0xea, 0x50, 0xb5, 0xd0, 0x53, 0xfa,
	0x55, 0xa3, 0x1c, 0x3d, 0xaf, 0x28, 0xd1, 0xa0, 0xe2, 0x9a, 0xdc, 0xe1, 0x21, 0x45, 0xb5, 0xd8,
	0x53, 0xfa, 0x8a, 0x91, 0xbe, 0x49, 0x17, 0xaa, 0xae, 0x37, 0xb7, 0x93, 0xe4, 0x5e, 0x9c, 0x5c,
	0x06, 0xa2, 0x2c, 0x77, 0x66, 0xc8, 0xb8, 0x39, 0xf3, 0xd5, 0x52, 0x4c, 0xba, 0x0c, 0xe8, 0xe7,
	0xd0, 0x94, 0xc3, 0x18, 0x78, 0x17, 0x22, 0xe3, 0xe4, 0x04, 0x2a, 0xae, 0x08, 0xc5, 0x93, 0xd5,
	0x86, 0xfb, 0x03, 0xb1, 0x49, 0x0a, 0x4d, 0x11, 0xfa, 0x1b, 0xd8, 0x5f, 0x12, 0x30, 0xdf, 0x9b,
	0x33, 0xfc, 0x43, 0x86, 0x0b, 0x38, 0x18, 0xb9, 0xae, 0x4c, 0xb0, 0x2d, 0x2c, 0xc5, 0x5f, 0xb0,
	0x9c, 0x80, 0x76, 0x89, 0x5c, 0x26, 0xf2, 0x3b, 0xe5, 0xbe, 0xb3, 0x7e, 0x0a, 0x8f, 0x2f, 0xd0,
	0x45, 0x8e, 0xbf, 0x5b, 0xf0, 0x0c, 0x5a, 0x49, 0x01, 0x95, 0xc8, 0x2b, 0xba, 0x06, 0x6a, 0xc3,
	0x83, 0xf7, 0x33, 0x9f, 0x2f, 0x3e, 0x20, 0x63, 0xa6, 0x8d, 0x82, 0x4b, 0xff, 0x08, 0x87, 0x63,
	0x87, 0xf1, 0x49, 0x68, 0xdb, 0xc8, 0xc4, 0x8e, 0x49, 0x97, 0xcc, 0xb9, 0x95, 0x95, 0x73, 0x1f,
	0x41, 0x5d, 0x6e, 0x36, 0x75, 0x28, 0x53, 0x0b, 0xbd, 0x62, 0xbf, 0x6a, 0xd4, 0xdc, 0xb4, 0x37,
	0xd3, 0xcf, 0xa0, 0xb3, 0xc6, 0x2a, 0xbe, 0x5c, 0xbe, 0x5a, 0x59, 0xaf, 0x1e, 0x40, 0x75, 0x44,
	0xe5, 0x18, 0x47, 0x50, 0xb7, 0xbc, 0x39, 0xc7, 0x6f, 0x7c, 0xfa, 0x15, 0x17, 0x29, 0x5e, 0xc4,
	0xae, 0x71, 0xc1, 0xf4, 0xe7, 0x00, 0x11, 0x5e, 0x34, 0xe8, 0x42, 0xd1, 0x14, 0xbc, 0xb5, 0x21,
	0xc8, 0xab, 0x8c, 0xa8, 0x11, 0x85, 0xf5, 0x57, 0x50, 0x18, 0xc5, 0x2b, 0x84, 0x81, 0x3b, 0x0d,
	0x90, 0x3a, 0x01, 0x5a, 0x5c, 0x2c, 0x58, 0x0b, 0x03, 0xd7, 0x10, 0x21, 0x42, 0x60, 0x2f, 0x6a,
	0x20, 0xa4, 0x1e, 0xff, 0xd6, 0x8f, 0xe1, 0xff, 0x09, 0x9a, 0x81, 0xf5, 0x45, 0x0e, 0x77, 0x00,
	0xa5, 0xbb, 0x10, 0x83, 0x85, 0x20, 0x48, 0x1e, 0xfa, 0x6b, 0x68, 0x48, 0xd8, 0xdf, 0xc8, 0x65,
	0xf8, 0xa3, 0xb8, 0x14, 0xfe, 0x04, 0x83, 0x7b, 0xc7, 0x42, 0x32, 0x82, 0xfa, 0xc4, 0xbc, 0x4f,
	0x25, 0x41, 0x3a, 0x6b, 0xf5, 0xc9, 0x48, 0x9a, 0xba, 0x9e, 0x10, 0x43, 0x5c, 0x43, 0x2d, 0xa3,
	0x42, 0xa2, 0x4b, 0xe0, 0x76, 0x69, 0xee, 0x20, 0x7b, 0x07, 0x8d, 0x4f, 0x3e, 0x35, 0xf9, 0x3f,
	0x4d, 0x64, 0x40, 0x63, 0x55, 0xe9, 0xe4, 0x58, 0x62, 0x77, 0x3a, 0x40, 0x7b, 0xb8, 0x0a, 0xcb,
	0xea, 0x7e, 0x0c, 0xcd, 0x4b, 0xe4, 0x59, 0xd3, 0x92, 0x47, 0x12, 0xbd, 0xc1, 0x00, 0x5a, 0x37,
	0x55, 0xc8, 0x26, 0x9f, 0xdf, 0x40, 0x3b, 0xc7, 0x36, 0xe1, 0x01, 0x9a, 0xb3, 0xdd, 0x9c, 0x5b,
	0x37, 0x7e, 0xa1, 0x0c, 0x6d, 0x68, 0x2d, 0x6d, 0x21, 0xaf, 0x6b, 0x40, 0x33, 0xe7, 0x17, 0xf2,
	0x24, 0xe5, 0xd8, 0x68, 0x4f, 0xed, 0xe9, 0xd6, 0x7c, 0xd2, 0x6a, 0x78, 0x16, 0xb9, 0x48, 0x36,
	0x38, 0x85, 0x72, 0xb4, 0x07, 0x65, 0xa4, 0x95, 0x71, 0x84, 0xa0, 0x22, 0xd9, 0x90, 0xa8, 0xbe,
	0x91, 0x52, 0x97, 0x0c, 0xe7, 0x52, 0xd4, 0xe9, 0xad, 0xda, 0xb2, 0x6c, 0xc5, 0x13, 0xda, 0x61,
	0x3e, 0x9c, 0x30, 0xbe, 0x85, 0xcf, 0x95, 0x24, 0xe1, 0xdf, 0xde, 0x96, 0xe3, 0xbf, 0x9d, 0x97,
	0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x53, 0xe2, 0x7a, 0x86, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationServiceClient interface {
	SaveLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
	GetLocation(ctx context.Context, in *GetLocationLocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
	UpdateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
	DeleteLocation(ctx context.Context, in *DeleteLocationLocationRequest, opts ...grpc.CallOption) (*DeletedLocationId, error)
	GetAllLocations(ctx context.Context, in *EmptyMessageRequest, opts ...grpc.CallOption) (*AllLocationsResponse, error)
	GetAllLocationsStream(ctx context.Context, in *EmptyMessageRequest, opts ...grpc.CallOption) (LocationService_GetAllLocationsStreamClient, error)
}

type locationServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocationServiceClient(cc *grpc.ClientConn) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) SaveLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/goloco.LocationService/SaveLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetLocation(ctx context.Context, in *GetLocationLocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/goloco.LocationService/GetLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) UpdateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/goloco.LocationService/UpdateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DeleteLocation(ctx context.Context, in *DeleteLocationLocationRequest, opts ...grpc.CallOption) (*DeletedLocationId, error) {
	out := new(DeletedLocationId)
	err := c.cc.Invoke(ctx, "/goloco.LocationService/DeleteLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetAllLocations(ctx context.Context, in *EmptyMessageRequest, opts ...grpc.CallOption) (*AllLocationsResponse, error) {
	out := new(AllLocationsResponse)
	err := c.cc.Invoke(ctx, "/goloco.LocationService/GetAllLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetAllLocationsStream(ctx context.Context, in *EmptyMessageRequest, opts ...grpc.CallOption) (LocationService_GetAllLocationsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LocationService_serviceDesc.Streams[0], "/goloco.LocationService/GetAllLocationsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &locationServiceGetAllLocationsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LocationService_GetAllLocationsStreamClient interface {
	Recv() (*LocationResponse, error)
	grpc.ClientStream
}

type locationServiceGetAllLocationsStreamClient struct {
	grpc.ClientStream
}

func (x *locationServiceGetAllLocationsStreamClient) Recv() (*LocationResponse, error) {
	m := new(LocationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LocationServiceServer is the server API for LocationService service.
type LocationServiceServer interface {
	SaveLocation(context.Context, *LocationRequest) (*LocationResponse, error)
	GetLocation(context.Context, *GetLocationLocationRequest) (*LocationResponse, error)
	UpdateLocation(context.Context, *LocationRequest) (*LocationResponse, error)
	DeleteLocation(context.Context, *DeleteLocationLocationRequest) (*DeletedLocationId, error)
	GetAllLocations(context.Context, *EmptyMessageRequest) (*AllLocationsResponse, error)
	GetAllLocationsStream(*EmptyMessageRequest, LocationService_GetAllLocationsStreamServer) error
}

// UnimplementedLocationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (*UnimplementedLocationServiceServer) SaveLocation(ctx context.Context, req *LocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLocation not implemented")
}
func (*UnimplementedLocationServiceServer) GetLocation(ctx context.Context, req *GetLocationLocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocation not implemented")
}
func (*UnimplementedLocationServiceServer) UpdateLocation(ctx context.Context, req *LocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (*UnimplementedLocationServiceServer) DeleteLocation(ctx context.Context, req *DeleteLocationLocationRequest) (*DeletedLocationId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLocation not implemented")
}
func (*UnimplementedLocationServiceServer) GetAllLocations(ctx context.Context, req *EmptyMessageRequest) (*AllLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLocations not implemented")
}
func (*UnimplementedLocationServiceServer) GetAllLocationsStream(req *EmptyMessageRequest, srv LocationService_GetAllLocationsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllLocationsStream not implemented")
}

func RegisterLocationServiceServer(s *grpc.Server, srv LocationServiceServer) {
	s.RegisterService(&_LocationService_serviceDesc, srv)
}

func _LocationService_SaveLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).SaveLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.LocationService/SaveLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).SaveLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.LocationService/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetLocation(ctx, req.(*GetLocationLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.LocationService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).UpdateLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DeleteLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLocationLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DeleteLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.LocationService/DeleteLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DeleteLocation(ctx, req.(*DeleteLocationLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetAllLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetAllLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.LocationService/GetAllLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetAllLocations(ctx, req.(*EmptyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetAllLocationsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocationServiceServer).GetAllLocationsStream(m, &locationServiceGetAllLocationsStreamServer{stream})
}

type LocationService_GetAllLocationsStreamServer interface {
	Send(*LocationResponse) error
	grpc.ServerStream
}

type locationServiceGetAllLocationsStreamServer struct {
	grpc.ServerStream
}

func (x *locationServiceGetAllLocationsStreamServer) Send(m *LocationResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LocationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goloco.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveLocation",
			Handler:    _LocationService_SaveLocation_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _LocationService_GetLocation_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _LocationService_UpdateLocation_Handler,
		},
		{
			MethodName: "DeleteLocation",
			Handler:    _LocationService_DeleteLocation_Handler,
		},
		{
			MethodName: "GetAllLocations",
			Handler:    _LocationService_GetAllLocations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllLocationsStream",
			Handler:       _LocationService_GetAllLocationsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goloco.proto",
}

// SuggestionServiceClient is the client API for SuggestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuggestionServiceClient interface {
	ListSuggestions(ctx context.Context, in *ListSuggestionsRequest, opts ...grpc.CallOption) (*ListSuggestionsResponse, error)
}

type suggestionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSuggestionServiceClient(cc *grpc.ClientConn) SuggestionServiceClient {
	return &suggestionServiceClient{cc}
}

func (c *suggestionServiceClient) ListSuggestions(ctx context.Context, in *ListSuggestionsRequest, opts ...grpc.CallOption) (*ListSuggestionsResponse, error) {
	out := new(ListSuggestionsResponse)
	err := c.cc.Invoke(ctx, "/goloco.SuggestionService/ListSuggestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestionServiceServer is the server API for SuggestionService service.
type SuggestionServiceServer interface {
	ListSuggestions(context.Context, *ListSuggestionsRequest) (*ListSuggestionsResponse, error)
}

// UnimplementedSuggestionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSuggestionServiceServer struct {
}

func (*UnimplementedSuggestionServiceServer) ListSuggestions(ctx context.Context, req *ListSuggestionsRequest) (*ListSuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSuggestions not implemented")
}

func RegisterSuggestionServiceServer(s *grpc.Server, srv SuggestionServiceServer) {
	s.RegisterService(&_SuggestionService_serviceDesc, srv)
}

func _SuggestionService_ListSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionServiceServer).ListSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.SuggestionService/ListSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionServiceServer).ListSuggestions(ctx, req.(*ListSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuggestionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goloco.SuggestionService",
	HandlerType: (*SuggestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSuggestions",
			Handler:    _SuggestionService_ListSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goloco.proto",
}

// AdServiceClient is the client API for AdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdServiceClient interface {
	GetAds(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error)
}

type adServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdServiceClient(cc *grpc.ClientConn) AdServiceClient {
	return &adServiceClient{cc}
}

func (c *adServiceClient) GetAds(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error) {
	out := new(AdResponse)
	err := c.cc.Invoke(ctx, "/goloco.AdService/GetAds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdServiceServer is the server API for AdService service.
type AdServiceServer interface {
	GetAds(context.Context, *AdRequest) (*AdResponse, error)
}

// UnimplementedAdServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdServiceServer struct {
}

func (*UnimplementedAdServiceServer) GetAds(ctx context.Context, req *AdRequest) (*AdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAds not implemented")
}

func RegisterAdServiceServer(s *grpc.Server, srv AdServiceServer) {
	s.RegisterService(&_AdService_serviceDesc, srv)
}

func _AdService_GetAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServiceServer).GetAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.AdService/GetAds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServiceServer).GetAds(ctx, req.(*AdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goloco.AdService",
	HandlerType: (*AdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAds",
			Handler:    _AdService_GetAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goloco.proto",
}

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchLocation(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchLocation(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/goloco.SearchService/SearchLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	SearchLocation(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) SearchLocation(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLocation not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_SearchLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goloco.SearchService/SearchLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchLocation(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goloco.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchLocation",
			Handler:    _SearchService_SearchLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goloco.proto",
}
